# The installer's file associations, from the build's own codec registry.
#
# Run in script mode by the `installer` target, after xpcog-list-extensions is
# built:
#
#   cmake -D XPCOG_LIST_EXTENSIONS=<exe> -D XPCOG_OUT_DIR=<dir> -P Associations.cmake
#
# It writes two NSIS fragments, together so they cannot disagree: one line per
# extension in each, the first adding XPCog to that extension's "Open with"
# list, the second taking it out again. The macros they call -- what is written
# where -- live in XPCog.nsi.in beside the keys that are not per extension.
#
# This replaced the installer running the player's own `--register` and
# `--unregister`. Those wrote HKCU whatever the install's scope, so a
# per-machine install offered XPCog to the one account that ran the installer
# and nobody else; the uninstaller needed the executable still on disk to
# undo them; and the WinUI player has no such switch to run. NSIS writes the
# same keys under SHCTX -- HKLM for everyone or HKCU for one user, the scope
# the install itself was given -- and its uninstaller removes exactly the list
# its installer wrote, since both were built from this one.

if(NOT XPCOG_LIST_EXTENSIONS OR NOT XPCOG_OUT_DIR)
    message(FATAL_ERROR "Associations.cmake: set XPCOG_LIST_EXTENSIONS and XPCOG_OUT_DIR")
endif()

execute_process(
    COMMAND "${XPCOG_LIST_EXTENSIONS}"
    OUTPUT_VARIABLE _output
    RESULT_VARIABLE _result
    ERROR_VARIABLE  _error)
if(NOT _result EQUAL 0)
    message(FATAL_ERROR
        "Associations.cmake: ${XPCOG_LIST_EXTENSIONS} failed (${_result}): ${_error}")
endif()

string(REPLACE "\r" "" _output "${_output}")
string(REPLACE "\n" ";" _extensions "${_output}")
list(REMOVE_ITEM _extensions "")
list(REMOVE_DUPLICATES _extensions)
list(SORT _extensions)

set(_add    "; Generated by packaging/windows/Associations.cmake -- do not edit.\n")
set(_remove "; Generated by packaging/windows/Associations.cmake -- do not edit.\n")
foreach(_extension IN LISTS _extensions)
    # Each one is pasted into a registry path inside an NSIS string, where a
    # quote ends the string, a $ starts a variable and a backslash starts a
    # subkey. Every extension a codec claims today is letters and digits; one
    # that is not is refused here rather than written somewhere unexpected.
    if(NOT _extension MATCHES "^[a-z0-9_+-]+$")
        message(FATAL_ERROR
            "Associations.cmake: refusing the extension \"${_extension}\": only "
            "lowercase letters, digits, '_', '+' and '-' are written to the registry.")
    endif()
    string(APPEND _add    "!insertmacro XPCogAssociate \"${_extension}\"\n")
    string(APPEND _remove "!insertmacro XPCogDissociate \"${_extension}\"\n")
endforeach()

list(LENGTH _extensions _count)
if(_count EQUAL 0)
    message(FATAL_ERROR "Associations.cmake: the codec registry claimed no extensions at all.")
endif()

file(WRITE "${XPCOG_OUT_DIR}/associations-install.nsh" "${_add}")
file(WRITE "${XPCOG_OUT_DIR}/associations-uninstall.nsh" "${_remove}")
message(STATUS "XPCog installer: offered for ${_count} file types")
