# What the installer ships, decided by walking what the build actually produced.
#
# Run in script mode, after a build, by the `installer` target:
#
#   cmake -D XPCOG_STAGE_DIR=<build>/bin -D XPCOG_OUT_DIR=<dir> -P Harvest.cmake
#
# --- Why harvest rather than install() -------------------------------------
#
# There are no install() rules for the application on Windows, and that is not an
# oversight -- app/CMakeLists.txt explains it under "Deployment: there is none".
# The DLLs beside XPCog.exe are put there by vcpkg's applocal post-build step,
# which resolves the whole transitive import table and knows about the triplet's
# debug/release name mangling. Re-deriving that list through
# install(RUNTIME_DEPENDENCY_SET) would mean asking a second, less informed tool
# the same question vcpkg already answered correctly, and the two answers would
# drift silently: the build tree would keep working while the installer shipped a
# folder that could not start.
#
# So the staged output directory *is* the deployment, and this reads it.
#
# --- Why an allowlist ------------------------------------------------------
#
# That directory holds more than the application: xpcog-cli.exe, three test
# binaries, and a .pdb and .ilk for each of them. A blocklist would have to be
# updated every time a target is added, and the failure mode of forgetting is
# shipping someone a 200 MB installer with the test suite inside it. An allowlist
# fails the other way -- a new file that should ship is left out and *reported*
# below, which is a build-log line rather than a release.

if(NOT XPCOG_STAGE_DIR OR NOT XPCOG_OUT_DIR)
    message(FATAL_ERROR "Harvest.cmake: set XPCOG_STAGE_DIR and XPCOG_OUT_DIR")
endif()

if(NOT EXISTS "${XPCOG_STAGE_DIR}/XPCog.exe")
    message(FATAL_ERROR
        "Harvest.cmake: no XPCog.exe in ${XPCOG_STAGE_DIR}. Build the app before "
        "packaging it.")
endif()

# The two asset directories, which assets/CMakeLists.txt stages beside the
# executable because xpcog::assetPath() looks relative to it. Named rather than
# globbed for subdirectories: a stray directory in the output tree -- CMake's own
# CMakeFiles, a profiler's dump -- is not an asset.
set(XPCOG_ASSET_DIRS soundfonts equalizer)

# ---------------------------------------------------------------------------
# Top level: the program, its out-of-process crash handler, and every DLL.
# ---------------------------------------------------------------------------
set(_ship "")
set(_skipped "")

file(GLOB _entries LIST_DIRECTORIES false "${XPCOG_STAGE_DIR}/*")
foreach(_entry IN LISTS _entries)
    get_filename_component(_name "${_entry}" NAME)
    if(_name STREQUAL "XPCog.exe"
            OR _name STREQUAL "crashpad_handler.exe"
            OR _name MATCHES "\\.dll$")
        list(APPEND _ship "${_entry}")
    else()
        list(APPEND _skipped "${_name}")
    endif()
endforeach()

list(SORT _ship)

# ---------------------------------------------------------------------------
# The NSIS fragments.
#
# Two files, generated together so they cannot disagree: whatever the first one
# writes, the second one removes. An uninstaller that deletes a list maintained by
# hand is an uninstaller that leaves a DLL behind on the release where someone
# forgot -- and RMDir /r $INSTDIR, the usual shortcut around that, is a recursive
# delete of a path the user was allowed to type on the directory page.
# ---------------------------------------------------------------------------
set(_install "; Generated by packaging/windows/Harvest.cmake -- do not edit.\n")
set(_remove  "; Generated by packaging/windows/Harvest.cmake -- do not edit.\n")

set(_bytes 0)

# Every path handed to NSIS is converted to backslashes first. makensis does not
# accept forward slashes in a source path: `File "C:/a/b.dll"` fails with "no
# files found" -- the wildcard-expansion message -- for a file that exists, and
# `!include` on such a path reports "could not find". Both read as the harvest
# having produced the wrong list rather than as the separator being rejected,
# which is an hour nobody needs to spend twice.
string(APPEND _install "SetOutPath \"$INSTDIR\"\n")
foreach(_file IN LISTS _ship)
    get_filename_component(_name "${_file}" NAME)
    file(SIZE "${_file}" _size)
    math(EXPR _bytes "${_bytes} + ${_size}")
    file(TO_NATIVE_PATH "${_file}" _native)
    string(APPEND _install "File \"${_native}\"\n")
    string(APPEND _remove "Delete \"$INSTDIR\\${_name}\"\n")
endforeach()

foreach(_dir IN LISTS XPCOG_ASSET_DIRS)
    if(NOT IS_DIRECTORY "${XPCOG_STAGE_DIR}/${_dir}")
        message(FATAL_ERROR
            "Harvest.cmake: ${XPCOG_STAGE_DIR}/${_dir} is missing. The assets are "
            "staged by the xpcog-assets target; build it before packaging.")
    endif()
    file(GLOB _files LIST_DIRECTORIES false "${XPCOG_STAGE_DIR}/${_dir}/*")
    list(SORT _files)
    string(APPEND _install "SetOutPath \"$INSTDIR\\${_dir}\"\n")
    foreach(_file IN LISTS _files)
        get_filename_component(_name "${_file}" NAME)
        file(SIZE "${_file}" _size)
        math(EXPR _bytes "${_bytes} + ${_size}")
        file(TO_NATIVE_PATH "${_file}" _native)
        string(APPEND _install "File \"${_native}\"\n")
        string(APPEND _remove "Delete \"$INSTDIR\\${_dir}\\${_name}\"\n")
    endforeach()
    # After its files, and only this directory: RMDir without /r declines to
    # remove a non-empty directory, so anything the user put here survives.
    string(APPEND _remove "RMDir \"$INSTDIR\\${_dir}\"\n")
endforeach()

# Add/Remove Programs shows this, and shows nothing if it is absent. In KiB,
# which is the unit EstimatedSize is documented in and the one place a factor of
# 1024 is not a rounding question.
math(EXPR _kib "${_bytes} / 1024")
string(APPEND _install "!define XPCOG_PAYLOAD_KIB ${_kib}\n")

file(WRITE "${XPCOG_OUT_DIR}/payload-install.nsh" "${_install}")
file(WRITE "${XPCOG_OUT_DIR}/payload-uninstall.nsh" "${_remove}")

list(LENGTH _ship _count)
math(EXPR _mib "${_bytes} / 1048576")
message(STATUS "XPCog installer payload: ${_count} files, ${_mib} MiB")
if(_skipped)
    list(SORT _skipped)
    list(JOIN _skipped " " _skipped_text)
    message(STATUS "  not shipped: ${_skipped_text}")
endif()
