// The OpenAPI document, and the five things that stop it drifting.
//
// The document is generated by walking the same table the router dispatches
// from, so it cannot describe an endpoint that does not exist. What that does
// not guarantee is that the pieces are filled in sensibly -- an empty summary, a
// path parameter nobody declared, a schema name with a typo in it -- and every
// one of those produces a document that looks fine and is wrong. So they are
// asserted here rather than noticed by whoever generates a client from it.

#include "Routes.hpp"

#include "xpcog/core/Version.hpp"
#include "xpcog/core/remote/RemoteServer.hpp"

#include <catch2/catch_test_macros.hpp>

#include <nlohmann/json.hpp>

#include <set>
#include <string>
#include <string_view>
#include <vector>

using namespace xpcog;
using namespace xpcog::remote;

namespace {

/// The `{name}` pieces of a path pattern.
std::vector<std::string> placeholders(std::string_view path) {
    std::vector<std::string> names;
    std::size_t              open = path.find('{');
    while (open != std::string_view::npos) {
        const std::size_t close = path.find('}', open);
        if (close == std::string_view::npos) {
            break;
        }
        names.emplace_back(path.substr(open + 1, close - open - 1));
        open = path.find('{', close);
    }
    return names;
}

/// Every "$ref" anywhere in the document.
void collectRefs(const nlohmann::json& node, std::vector<std::string>& out) {
    if (node.is_object()) {
        for (const auto& [key, value] : node.items()) {
            if (key == "$ref" && value.is_string()) {
                out.push_back(value.get<std::string>());
            } else {
                collectRefs(value, out);
            }
        }
    } else if (node.is_array()) {
        for (const nlohmann::json& element : node) {
            collectRefs(element, out);
        }
    }
}

nlohmann::json document() {
    nlohmann::json parsed =
        nlohmann::json::parse(RemoteServer::openApiDocument(), nullptr, false);
    REQUIRE_FALSE(parsed.is_discarded());
    return parsed;
}

}  // namespace

TEST_CASE("every route has an operation id and a summary, and they are unique",
          "[remote]") {
    std::set<std::string_view> seen;
    for (const Route& route : routes()) {
        INFO("route: " << route.path);
        CHECK_FALSE(route.operationId.empty());
        CHECK_FALSE(route.summary.empty());
        // A duplicate id generates a client with two methods of one name, which
        // fails somewhere far from here.
        CHECK(seen.insert(route.operationId).second);
    }
}

TEST_CASE("every path placeholder is declared, and every declaration is used",
          "[remote]") {
    for (const Route& route : routes()) {
        INFO("route: " << route.path);

        std::set<std::string> declared;
        for (const Param& param : route.params) {
            if (param.in == In::Path) {
                declared.insert(std::string{param.name});
            }
        }

        std::set<std::string> used;
        for (const std::string& name : placeholders(route.path)) {
            used.insert(name);
        }

        // Both directions. An undeclared {id} is a parameter missing from the
        // document; a declared one that is not in the path is a parameter a
        // client will send and nothing will read.
        CHECK(declared == used);
    }
}

TEST_CASE("every schema a route names exists", "[remote]") {
    std::set<std::string_view> known;
    for (const Schema& schema : schemas()) {
        known.insert(schema.name);
    }

    for (const Route& route : routes()) {
        INFO("route: " << route.path);
        if (!route.requestSchema.empty()) {
            CHECK(known.count(route.requestSchema) == 1);
        }
        if (!route.responseSchema.empty()) {
            CHECK(known.count(route.responseSchema) == 1);
        }
    }
}

TEST_CASE("no schema is defined and never referenced", "[remote]") {
    std::set<std::string_view> referenced;
    for (const Route& route : routes()) {
        if (!route.requestSchema.empty()) {
            referenced.insert(route.requestSchema);
        }
        if (!route.responseSchema.empty()) {
            referenced.insert(route.responseSchema);
        }
    }
    // Reached only through another schema's $ref, not from a route directly.
    referenced.insert("Error");
    referenced.insert("Track");

    for (const Schema& schema : schemas()) {
        INFO("schema: " << schema.name);
        CHECK(referenced.count(schema.name) == 1);
    }
}

TEST_CASE("the document parses and every $ref in it resolves", "[remote]") {
    const nlohmann::json parsed = document();

    std::vector<std::string> refs;
    collectRefs(parsed, refs);
    CHECK_FALSE(refs.empty());

    for (const std::string& reference : refs) {
        INFO("$ref: " << reference);
        constexpr std::string_view kPrefix = "#/components/schemas/";
        REQUIRE(reference.rfind(kPrefix, 0) == 0);
        const std::string name = reference.substr(kPrefix.size());
        CHECK(parsed.at("components").at("schemas").contains(name));
    }
}

TEST_CASE("the document says which version and which OpenAPI", "[remote]") {
    const nlohmann::json parsed = document();

    // 3.1 rather than 3.0, because the nullable fields here are expressed as a
    // type array -- ["integer", "null"] -- which 3.0 has no spelling for.
    CHECK(parsed.at("openapi").get<std::string>() == "3.1.0");
    CHECK(parsed.at("info").at("version").get<std::string>() ==
          std::string{kVersionString});
}

TEST_CASE("every route in the table is in the document", "[remote]") {
    const nlohmann::json parsed = document();

    for (const Route& route : routes()) {
        const std::string path{route.path};
        INFO("route: " << path);
        REQUIRE(parsed.at("paths").contains(path));

        std::string method{methodName(route.method)};
        for (char& c : method) {
            c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
        }
        CHECK(parsed.at("paths").at(path).contains(method));
    }
}

TEST_CASE("the document declares the bearer scheme it actually enforces",
          "[remote]") {
    const nlohmann::json parsed = document();

    // A document that did not say so would send a client into a wall of 401s
    // with nothing to explain them.
    CHECK(parsed.at("components").at("securitySchemes").at("bearerAuth").at("scheme") ==
          "bearer");
    CHECK_FALSE(parsed.at("security").empty());
}

TEST_CASE("a write route documents the answers only a write can give",
          "[remote]") {
    const nlohmann::json parsed = document();

    // 409 is the one worth pinning: it is what a silently-declining command
    // becomes, and a client that does not know to expect it will read a decline
    // as a success.
    const nlohmann::json& stop =
        parsed.at("paths").at("/api/v1/transport/stop").at("post");
    CHECK(stop.at("responses").contains("409"));
    CHECK(stop.at("responses").contains("403"));

    const nlohmann::json& status = parsed.at("paths").at("/api/v1/status").at("get");
    CHECK_FALSE(status.at("responses").contains("409"));
}

TEST_CASE("a deferred route documents 202 rather than 200", "[remote]") {
    const nlohmann::json parsed = document();
    const nlohmann::json& add =
        parsed.at("paths").at("/api/v1/playlist/tracks").at("post");

    CHECK(add.at("responses").contains("202"));
    CHECK_FALSE(add.at("responses").contains("200"));
}
