// VGM, S98, DRO and GYM -- chip register logs, replayed on emulated hardware.
//
// Port of Cog Plugins/libvgmPlayer, on ValleyBell's libvgm (ports/libvgm).
// These four formats are not music files in the ordinary sense and not tracker
// modules either: each is a timestamped log of everything that was written to a
// sound chip's registers, so playing one means emulating the chip and feeding it
// the writes at the right moments. libvgm carries around fifty such emulators --
// the YM2612 in a Mega Drive, the SN76489 in a Master System, the OPL family,
// the SCC, the C140, the Namco WSG -- which is why one library covers a shelf of
// consoles.
//
// **The priority is 1.25, and this is one of the few places in the tree that
// needs a number at all.** Every extension here is claimed by something else
// already: `.vgm` and `.vgz` by both Game_Music_Emu and vgmstream, `.gym` by
// Game_Music_Emu, `.dro` by AdPlug and vgmstream. Unlike `.ahx` or `.mus`,
// content does not settle it -- all of them genuinely read these files, they
// just read fewer chips or read them less accurately. So something has to say
// which is preferred, and 1.25 is Cog's number for the same reason.
//
// Worth knowing what the number is and is not doing. At the *default* priority
// this decoder would still win today, because ties break by registration order
// and codecs/CMakeLists.txt happens to enter this directory before gme's. That
// is an ordering accident rather than a decision, which is exactly why the
// number is here: dropped below the catch-alls, a Mega CD VGM opens as
// Game_Music_Emu's "Sega MegaCD / SegaCD" instead, with a different length and
// a different emulator behind it. Checked by doing it.
//
// Cog gets the same effect a different way: its container appends `#0` to every
// URL, with the comment "these are included so they can override AdPlug and
// VGMStream". That is a fragment carrying no information, on a format with no
// subsongs, doing a priority's job. Here the priority does it and there is no
// container at all.
//
// Three other differences from Cog:
//
//   * **The length includes the loops, the fade and the trailing silence.** Cog
//     reports `Tick2Second(GetTotalTicks())`, which is one pass through the file
//     and nothing else -- while PlayerA goes on to play `loopCount` passes, fade
//     over the configured seconds, and add half a second of silence. On a
//     looping VGM, which is most of them, Cog's playlist shows roughly half the
//     time the track actually takes. `GetTotalTime()` with the loop, fade and
//     silence flags is the number PlayerA is actually working to.
//
//   * **The end of the track comes from the player's own state** rather than
//     from an event callback with a flag behind it. PlayerA raises
//     PLAYSTATE_FIN when the fade and the trailing silence are both done
//     (playera.cpp, `_myPlayState |= PLAYSTATE_FIN`), which is the same moment
//     PLREVT_END fires and needs no plumbing to observe. It matters that this is
//     asked rather than inferred: PlayerA::Render fills the buffer with silence
//     and reports success when the player has stopped, so a short read never
//     signals the end.
//
//   * **The OPL4 sample ROM is optional.** See requestFile() below.

#include "common/SourceBytes.hpp"
#include "common/TextEncoding.hpp"

#include "xpcog/core/Plugin.hpp"
#include "xpcog/core/PluginRegistry.hpp"
#include "xpcog/core/Settings.hpp"

#include <vgm/player/droplayer.hpp>
#include <vgm/player/gymplayer.hpp>
#include <vgm/player/playera.hpp>
#include <vgm/player/playerbase.hpp>
#include <vgm/player/s98player.hpp>
#include <vgm/player/vgmplayer.hpp>
#include <vgm/utils/DataLoader.h>
#include <vgm/utils/FileLoader.h>
#include <vgm/utils/MemoryLoader.h>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <memory>
#include <span>
#include <string>
#include <string_view>
#include <vector>

/// The OPL4 wavetable ROM, if this build has one. Generated by
/// codecs/libvgm/CMakeLists.txt; the size is zero when it does not.
extern "C" {
extern const unsigned char kYrw801Rom[];
extern const unsigned int  kYrw801RomSize;
}

namespace xpcog {
namespace {

constexpr std::string_view kExtensionList[] = {"vgm", "vgz", "s98", "dro", "gym"};
constexpr std::span<const std::string_view> kExtensions{kExtensionList};

/// Above every other decoder that claims these extensions, and Cog's number.
/// See the note at the top of this file.
constexpr Priority kLibVgmPriority = 1.25F;

constexpr std::uint32_t kChannels = 2;
/// libvgm mixes at 24-bit internal scale (playera.cpp, SampleConv_toS32 clamps
/// to +/-0x800000 before shifting), so 24 bits out is the mixer's full precision
/// and anything wider is padding. Cog asks for the same.
constexpr std::uint8_t kBitsPerSample = 24;

/// What Cog falls back to when synthSampleRate is unset or out of range, and
/// the clamp it applies.
constexpr int kDefaultRate = 44100;
constexpr int kMinRate     = 8000;
constexpr int kMaxRate     = 192000;

constexpr int kMaxLoopCount = 10;

/// PlayerA renders at most this many frames per call and silently clamps a
/// larger request (playera.cpp: `if (smplCount > _smplBuf.size())`), so the read
/// loop has to be prepared for a short answer. Cog's number.
constexpr std::uint32_t kPlayerBufferFrames = 2048;

/// Fixed point 16.16; 0x10000 is unity.
constexpr std::int32_t kMasterVolume = 0x10000;

[[nodiscard]] int preferredRate(const Settings* settings) {
    if (settings == nullptr) {
        return kDefaultRate;
    }
    const int rate = settings->SynthSampleRate();
    return (rate < kMinRate || rate > kMaxRate) ? kDefaultRate : rate;
}

/// A four-character code as text: "VGM ", "S98 ", "DRO ", "GYM ".
[[nodiscard]] std::string fourCC(std::uint32_t code) {
    std::string out(4, '\0');
    for (int i = 0; i < 4; ++i) {
        out[static_cast<std::size_t>(i)] =
            static_cast<char>((code >> ((3 - i) * 8)) & 0xFF);
    }
    while (!out.empty() && (out.back() == ' ' || out.back() == '\0')) {
        out.pop_back();
    }
    return out;
}

struct LoaderDeleter {
    void operator()(DATA_LOADER* loader) const noexcept {
        if (loader != nullptr) {
            DataLoader_Deinit(loader);
        }
    }
};
using LoaderPtr = std::unique_ptr<DATA_LOADER, LoaderDeleter>;

class LibVgmDecoder final : public IDecoder {
public:
    ~LibVgmDecoder() override { LibVgmDecoder::close(); }

    void setSettings(const Settings* settings) override { settings_ = settings; }

    bool open(ISource* source) override {
        close();
        if (source == nullptr) {
            return false;
        }

        auto data = codecs::readAllBytes(*source);
        if (!data || data->empty()) {
            return false;
        }
        fileData_ = std::move(*data);
        // Kept for requestFile(): a VGM asking for its OPL4 ROM is asking for a
        // file beside itself, and this is the only place that knows where that
        // is.
        trackUrl_ = source->url();

        rate_ = preferredRate(settings_);

        player_ = std::make_unique<PlayerA>();
        // PlayerA takes ownership of each engine and deletes them in its own
        // destructor (UnregisterAllPlayers), so these are not leaked.
        player_->RegisterPlayerEngine(new VGMPlayer);
        player_->RegisterPlayerEngine(new S98Player);
        player_->RegisterPlayerEngine(new DROPlayer);
        player_->RegisterPlayerEngine(new GYMPlayer);
        player_->SetFileReqCallback(&LibVgmDecoder::requestFile, this);

        {
            PlayerA::Config config   = player_->GetConfiguration();
            config.masterVol         = kMasterVolume;
            config.loopCount         = static_cast<std::uint32_t>(loopPasses());
            config.fadeSmpls         = fadeFrameCount();
            // Cog's half second. It is what stops a chip's last note being cut
            // off the instant the log runs out.
            config.endSilenceSmpls   = static_cast<std::uint32_t>(rate_ / 2);
            config.pbSpeed           = 1.0;
            player_->SetConfiguration(config);
        }
        if (player_->SetOutputSettings(static_cast<std::uint32_t>(rate_), kChannels,
                                       kBitsPerSample, kPlayerBufferFrames) != 0) {
            close();
            return false;
        }

        loader_ = LoaderPtr{MemoryLoader_Init(
            reinterpret_cast<const std::uint8_t*>(fileData_.data()),
            static_cast<std::uint32_t>(fileData_.size()))};
        if (!loader_) {
            close();
            return false;
        }
        // Enough for every one of the four headers. The loader reads the rest on
        // demand, which for a .vgz means it does not inflate the whole file to
        // find out it is not one.
        DataLoader_SetPreloadBytes(loader_.get(), 0x100);
        if (DataLoader_Load(loader_.get()) != 0 ||
            player_->LoadFile(loader_.get()) != 0) {
            close();
            return false;
        }

        applyLoopCount(loopPasses());

        PlayerBase* engine = player_->GetPlayer();
        if (engine == nullptr) {
            close();
            return false;
        }
        readTags(*engine);

        // Everything PlayerA will render: the passes, the fade, and the
        // trailing silence. Negative means the file never ends -- a DRO or GYM
        // log with no terminator -- and there is no length in that, so it falls
        // back on the same setting every other endless format here uses.
        const double seconds = player_->GetTotalTime(
            PLAYTIME_LOOP_INCL | PLAYTIME_WITH_FADE | PLAYTIME_WITH_SLNC);
        totalFrames_ =
            seconds > 0.0
                ? static_cast<std::int64_t>(seconds * static_cast<double>(rate_))
                : defaultLengthFrames();

        format_.sampleRate    = static_cast<double>(rate_);
        format_.channels      = kChannels;
        format_.channelConfig = 0x3;  // FL | FR
        format_.format        = SampleFormat::S24;
        format_.bitsPerSample = kBitsPerSample;

        scratch_.assign(static_cast<std::size_t>(kFramesPerRead) * format_.bytesPerFrame(),
                        std::byte{0});
        framePos_ = 0;

        return player_->Start() == 0;
    }

    [[nodiscard]] TrackProperties properties() const override {
        TrackProperties props;
        props.format      = format_;
        props.totalFrames = totalFrames_;
        props.seekable    = true;
        props.lossless    = false;
        props.codec       = codec_.empty() ? std::string{"libvgm"} : codec_;
        props.encoding    = "synthesized";
        return props;
    }

    [[nodiscard]] MetadataMap metadata() const override { return tags_; }

    bool readAudio(AudioChunk& out) override {
        if (!player_) {
            return false;
        }

        // Asked per read rather than latched at open: the listener can switch
        // repeat-one on part-way through and expects the fade to stop coming.
        // Zero means "loop for ever" to PlayerA.
        const bool endless = loopForever(settings_);
        applyLoopCount(endless ? 0 : loopPasses());

        // PLAYSTATE_FIN, not a short render: PlayerA fills the buffer with
        // silence and reports success once the player has stopped, so this is
        // the only thing that says the track is over.
        if ((player_->GetState() & PLAYSTATE_FIN) != 0) {
            return false;
        }

        const std::uint32_t bytesPerFrame = format_.bytesPerFrame();
        std::size_t         filled        = 0;
        while (filled < static_cast<std::size_t>(kFramesPerRead)) {
            const std::size_t want =
                std::min<std::size_t>(static_cast<std::size_t>(kFramesPerRead) - filled,
                                      kPlayerBufferFrames);
            const std::uint32_t rendered = player_->Render(
                static_cast<std::uint32_t>(want * bytesPerFrame),
                scratch_.data() + (filled * bytesPerFrame));

            const std::size_t frames = rendered / bytesPerFrame;
            filled += frames;
            if (frames < want) {
                break;
            }
        }
        if (filled == 0) {
            return false;
        }

        out.clear();
        out.setFormat(format_);
        out.lossless        = false;
        out.streamTimestamp = static_cast<double>(framePos_) / static_cast<double>(rate_);
        out.streamTimeRatio = 1.0;

        std::byte* dst = out.allocFrames(filled);
        std::memcpy(dst, scratch_.data(), filled * bytesPerFrame);
        out.setFrameCount(filled);

        framePos_ += static_cast<std::int64_t>(filled);
        return true;
    }

    /// libvgm seeks by re-running the log, which it does internally -- there is
    /// no state here to unwind, so this is one call.
    std::int64_t seek(std::int64_t frame) override {
        if (!player_) {
            return -1;
        }
        frame = std::max<std::int64_t>(frame, 0);
        if (player_->Seek(PLAYPOS_SAMPLE, static_cast<std::uint32_t>(frame)) != 0) {
            return -1;
        }
        framePos_ = frame;
        return frame;
    }

    void close() override {
        if (player_) {
            player_->Stop();
            player_->UnloadFile();
            player_.reset();
        }
        // After the player, which holds it while a file is loaded.
        loader_.reset();
        fileData_.clear();
        fileData_.shrink_to_fit();
        scratch_.clear();
        tags_ = {};
        codec_.clear();
        framePos_ = 0;
    }

private:
    static constexpr std::int64_t kFramesPerRead = 2048;

    [[nodiscard]] int loopPasses() const {
        const int loops =
            (settings_ != nullptr) ? settings_->SynthDefaultLoopCount() : 2;
        return std::clamp(loops, 1, kMaxLoopCount);
    }

    [[nodiscard]] std::uint32_t fadeFrameCount() const {
        const double seconds =
            (settings_ != nullptr) ? settings_->SynthDefaultFadeSeconds() : 8.0;
        return static_cast<std::uint32_t>(
            std::ceil(std::max(0.0, seconds) * static_cast<double>(rate_)));
    }

    [[nodiscard]] std::int64_t defaultLengthFrames() const {
        const double seconds =
            (settings_ != nullptr) ? settings_->SynthDefaultSeconds() : 150.0;
        return static_cast<std::int64_t>(std::max(0.0, seconds) *
                                         static_cast<double>(rate_));
    }

    /// Sets the loop count, honouring a VGM's own header if it has one.
    ///
    /// A VGM can say "my loop is worth half a play" (LoopModifier) or "count my
    /// loop as N" (LoopBase), which is how a file whose loop is one bar asks not
    /// to be played twice through one bar. GetModifiedLoopCount folds the
    /// listener's preference into that; the other three formats have no such
    /// field.
    void applyLoopCount(int passes) {
        const auto loops = static_cast<std::uint32_t>(passes);
        player_->SetLoopCount(loops);

        PlayerBase* engine = player_->GetPlayer();
        if (engine != nullptr && engine->GetPlayerType() == FCC_VGM) {
            auto* vgm = dynamic_cast<VGMPlayer*>(engine);
            if (vgm != nullptr) {
                player_->SetLoopCount(vgm->GetModifiedLoopCount(loops));
            }
        }
    }

    void readTags(PlayerBase& engine) {
        const auto put = [this](std::string_view key, const char* value) {
            if (value != nullptr && *value != '\0') {
                tags_.set(key, codecs::toUtf8(value));
            }
        };

        // A flat null-terminated list of key/value pairs. Cog's mapping, which
        // puts the game in `album` -- for a chip log the "album" is the game and
        // the "title" is the cue.
        const char* const* list = engine.GetTags();
        for (const char* const* tag = list; tag != nullptr && *tag != nullptr;
             tag += 2) {
            const std::string_view key{tag[0]};
            if (key == "TITLE") {
                put("title", tag[1]);
            } else if (key == "ARTIST") {
                put("artist", tag[1]);
            } else if (key == "GAME") {
                put("album", tag[1]);
            } else if (key == "DATE") {
                put("date", tag[1]);
            } else if (key == "SYSTEM") {
                // Not in Cog's list, and it is the one field that says which
                // machine this is a recording of -- which for a shelf of chip
                // logs is what a listener actually sorts by.
                put("genre", tag[1]);
            } else if (key == "COMMENT") {
                put("comment", tag[1]);
            }
        }

        PLR_SONG_INFO info{};
        if (engine.GetSongInfo(info) == 0) {
            // "VGM v1.71" -- the version is BCD, so the digits are the nibbles.
            char text[32];
            std::snprintf(text, sizeof(text), "%s v%X.%02X", fourCC(info.format).c_str(),
                          info.fileVerMaj, info.fileVerMin);
            codec_ = text;
        }
    }

    /// Answers libvgm when a player asks for a file it needs.
    ///
    /// In practice there is exactly one: `yrw801.rom`, the 2 MB Yamaha wavetable
    /// the YMF278B (OPL4) plays its sample-based instruments out of. A VGM using
    /// that chip can carry the samples itself, and most do; the ones that do not
    /// expect the player to have the ROM.
    ///
    /// It is looked for in two places rather than assumed:
    ///
    ///   1. compiled in, if `codecs/libvgm/data/yrw801.rom` was present at build
    ///      time -- which it is in this tree, so this is the path that runs;
    ///   2. otherwise, beside the file being played.
    ///
    /// Cog only has the first, as a 14 MB header. Keeping the ROM as a binary
    /// that CMake turns into an array costs the same 2 MB in the binary and
    /// saves 12 MB in the repository, and having the second means a build
    /// without the ROM still works for somebody who keeps one next to their
    /// files.
    ///
    /// Finding neither is not a failure either. libvgm logs a warning and plays
    /// the chip's FM half, which is most of what an OPL4 track is; only its
    /// sample-based instruments go quiet. That is a far better outcome than a
    /// file that will not open, and it is confined to one chip.
    static DATA_LOADER* requestFile(void* userParam, PlayerBase* /*player*/,
                                    const char* fileName) {
        if (fileName == nullptr) {
            return nullptr;
        }

        const auto load = [](DATA_LOADER* loader) -> DATA_LOADER* {
            if (loader == nullptr) {
                return nullptr;
            }
            if (DataLoader_Load(loader) == 0) {
                return loader;
            }
            DataLoader_Deinit(loader);
            return nullptr;
        };

        if (std::strcmp(fileName, "yrw801.rom") == 0 && kYrw801RomSize > 0) {
            return load(MemoryLoader_Init(kYrw801Rom, kYrw801RomSize));
        }

        // Beside the track. Only for a local file: FileLoader_Init takes a path,
        // so there is nothing to hand it for an archive member or an HTTP
        // stream, and a companion ROM is not something either of those carries.
        const auto* self = static_cast<const LibVgmDecoder*>(userParam);
        if (self == nullptr) {
            return nullptr;
        }
        const auto path = self->trackUrl_.localPath();
        if (!path) {
            return nullptr;
        }
        std::error_code    error;
        const std::filesystem::path beside = path->parent_path() / fileName;
        if (!std::filesystem::exists(beside, error)) {
            return nullptr;
        }
        return load(FileLoader_Init(beside.string().c_str()));
    }

    const Settings* settings_ = nullptr;

    std::unique_ptr<PlayerA> player_;
    LoaderPtr                loader_;
    std::vector<std::byte>   fileData_;
    Url                      trackUrl_;

    AudioFormat  format_{};
    int          rate_        = kDefaultRate;
    std::int64_t totalFrames_ = 0;
    std::int64_t framePos_    = 0;

    MetadataMap tags_;
    std::string codec_;

    std::vector<std::byte> scratch_;
};

}  // namespace
}  // namespace xpcog

void xpcog_register_libvgm(xpcog::PluginRegistry& r) {
    r.addDecoder({
        .name       = "LibVgmDecoder",
        .priority   = xpcog::kLibVgmPriority,
        .extensions = xpcog::kExtensions,
        .mimeTypes  = {},
        .create     = []() -> xpcog::DecoderPtr {
            return std::make_unique<xpcog::LibVgmDecoder>();
        },
        .available = nullptr,
    });
}
