#!/usr/bin/env python3
"""Regenerates uicore/locale/xpcog.pot from the marked strings in uicore/ and both frontends.

What xgettext would do, and it is here for the reason cmake/CompileCatalog.cmake
exists rather than a call to msgfmt: gettext is not a tool this project needs
anywhere else, and the one platform most of this is built on is the one least
likely to have it. Python is not a build dependency either -- nothing in CMake
runs this -- but a template is regenerated by a person once in a while, not by
CI on every commit, and asking that person for a Python they already have is a
much smaller imposition than asking for a gettext they do not.

    python tools/extract-messages.py

It reads `tr()`, `trn()`, `trf()` and `XPCOG_TRANSLATE()` from
uicore/src/Translations.hpp -- also as `app::tr()` and the rest, the spelling
the WinUI player uses -- and `_()` in the GTK player's Blueprint files, and
nothing else. Adjacent string literals are joined, so a message wrapped across
four lines comes out as one.

Escapes are decoded and the .pot carries raw UTF-8, which is what every other .po
in the world does and what the catalogue compiler wants: it copies the msgid into
a C++ string literal verbatim, and every source here is compiled as UTF-8.

**It does not merge.** The output is a fresh template; uicore/locale/*.po are
updated against it by hand or with msgmerge if you have one.

It does, however, *report* what each catalogue is missing and what it still
carries that the sources no longer say. That report is the whole reason the
"it does not merge" limitation is survivable: a message whose English is
reworded is a new msgid, the old translation goes on sitting in the .po
answering a question nobody asks any more, and the new one falls back to
English -- in one row of one pane, which is exactly the kind of thing that
ships. Rewording three labels is how this got written.
"""
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Every root, and all of them are needed. uicore/src holds the command tables,
# the playback controller's messages and the undo labels; app-winui/src and
# app-gtk/src hold the windows, app-gtk/ui the GTK interface files. A run that
# forgot one would read as a mass deletion in the template and look like a
# legitimate diff.
SRC = [os.path.join(ROOT, 'uicore', 'src'), os.path.join(ROOT, 'app-winui', 'src'),
       os.path.join(ROOT, 'app-gtk', 'src'), os.path.join(ROOT, 'app-gtk', 'ui')]

# The GTK frontend's interface files. Blueprint spells a translatable string
# `_("...")` exactly as C does, with the same escapes, so the same scanner reads
# them -- and GtkBuilder looks them up through gettext under the same domain
# the compiled-in catalogue is written out as, so they belong in one template.
UI_EXTENSIONS = ('.blp',)
OUT = os.path.join(ROOT, 'uicore', 'locale', 'xpcog.pot')

STRING = re.compile(r'\s*"((?:[^"\\]|\\.)*)"')
# The lookbehind excludes `.` and `:` as well as word characters: without them
# this would also match `foo.tr(` and `ns::tr(`, and a marker that silently
# harvests a method call is the kind of thing found much later, by a translator
# asking what a string is. The one qualified spelling that *is* a marker is
# `app::tr(` -- the WinUI player calls the lookup that way from namespace
# xpcog::winui -- and it is allowed by name.
KEYWORD = re.compile(
    r'(?<![A-Za-z0-9_.:])(?:app::)?(_|tr|trn|trf|XPCOG_TRANSLATE)\(')

# There was once a list here of markers that could carry only ASCII: wx's `_()`
# turned its literal into a wxString through the current 8-bit locale on
# Windows, and an em dash came out as mojibake. wx went in 3.0.0, and every
# marker left is UTF-8 in and UTF-8 out.

# Markers whose second literal is a plural form rather than another argument.
PLURAL_KEYWORDS = ('trn',)

SIMPLE = {'n': '\n', 't': '\t', 'r': '\r', '\\': '\\', '"': '"', "'": "'"}

# Messages shown by the application but written somewhere the scan cannot see
# them. Only core's playlist headings so far: core links no toolkit and so has no
# `_()` to mark them with, and PlaylistColumns looks them up by their English
# text -- see the comment there. Every one but this is also an info-panel field
# and is therefore already found above.
EXTERNAL = [
    ("#. The playlist's track-number column heading. A symbol rather than a\n"
     "#. word, and it has to stay short: the column is 44 dialog units wide.\n"
     "#: core/src/library/PlaylistView.cpp\n", "#"),
]

HEADER = '''# XPCog, an audio player ported from Cog.
# Copyright (C) 2026 the XPCog authors.
# This file is distributed under the same licence as XPCog.
#
# Regenerated with tools/extract-messages.py; see uicore/locale/README.md.
#
msgid ""
msgstr ""
"Project-Id-Version: XPCog\\n"
"Report-Msgid-Bugs-To: https://github.com/losnoco/XPCog/issues\\n"
"Language: \\n"
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\\n"

'''


def decode(raw):
    """C escapes to text.

    `\\xNN` is read as exactly two digits, which is how the sources write them --
    and why a couple of those sources split a literal in two, so that the digits
    of the text after an escape are not swallowed by it.
    """
    out = bytearray()
    i = 0
    while i < len(raw):
        if raw[i] != '\\':
            out += raw[i].encode('utf-8')
            i += 1
            continue
        kind = raw[i + 1]
        if kind == 'x':
            out.append(int(raw[i + 2:i + 4], 16))
            i += 4
        else:
            out += SIMPLE[kind].encode('utf-8')
            i += 2
    return out.decode('utf-8')


def escape(text):
    return (text.replace('\\', '\\\\').replace('"', '\\"')
                .replace('\n', '\\n').replace('\t', '\\t'))


def po_field(keyword, text):
    """One PO field, broken at newlines the way gettext writes a long message."""
    if '\n' not in text and len(text) < 68:
        return '%s "%s"\n' % (keyword, escape(text))

    pieces = []
    lines = text.split('\n')
    for index, line in enumerate(lines):
        if index < len(lines) - 1:
            line += '\n'
        elif not line:
            continue
        pieces.append(line)

    return '%s ""\n' % keyword + ''.join('"%s"\n' % escape(p) for p in pieces)


def read_literal(text, i):
    parts = []
    while True:
        match = STRING.match(text, i)
        if not match:
            break
        parts.append(match.group(1))
        i = match.end()
    return decode(''.join(parts)), i


def scan(path):
    text = io.open(path, encoding='utf-8').read()
    found = []
    for match in KEYWORD.finditer(text):
        keyword = match.group(1)
        value, i = read_literal(text, match.end())
        # `_(` also matches a member being initialised -- `settings_(settings)`
        # -- and `tr(` a call taking a variable; neither has a string literal
        # after it.
        if not value:
            continue
        line = text.count('\n', 0, match.start()) + 1

        plural = None
        if keyword in PLURAL_KEYWORDS and i < len(text) and text[i] == ',':
            plural, i = read_literal(text, i + 1)
        if keyword == 'trn' and plural is None:
            raise SystemExit('%s:%d: %s needs two literals' % (path, line, keyword))

        found.append((line, value, plural))
    return found


PO_FIELD = re.compile(r'^(msgid_plural|msgid|msgstr(?:\[\d+\])?) "(.*)"$')


def unescape(text):
    out, i = [], 0
    while i < len(text):
        if text[i] == '\\':
            out.append(SIMPLE[text[i + 1]])
            i += 2
        else:
            out.append(text[i])
            i += 1
    return ''.join(out)


def catalogue_msgids(path):
    """Every msgid in a .po, header and obsolete entries excluded."""
    found, msgid, keyword = set(), None, None
    for line in io.open(path, encoding='utf-8'):
        line = line.rstrip('\n')
        if not line:
            if msgid:
                found.add(msgid)
            msgid, keyword = None, None
        elif line.startswith('#'):
            continue
        elif PO_FIELD.match(line):
            match = PO_FIELD.match(line)
            keyword = match.group(1)
            if keyword == 'msgid':
                msgid = unescape(match.group(2))
        elif line.startswith('"') and keyword == 'msgid':
            msgid += unescape(line[1:-1])
    if msgid:
        found.add(msgid)
    return found


def report_drift(wanted):
    """What each catalogue lacks, and what it is still carrying pointlessly.

    `wanted` is every msgid the template ended up with -- the scanned ones and
    the EXTERNAL rows alike, or those would be reported obsolete on every run.
    """
    directory = os.path.dirname(OUT)
    for name in sorted(os.listdir(directory)):
        if not name.endswith('.po'):
            continue
        path = os.path.join(directory, name)
        have = catalogue_msgids(path)
        missing = sorted(m for m in wanted if m not in have)
        obsolete = sorted(m for m in have if m not in wanted)

        if not missing and not obsolete:
            print('%s: up to date' % name, file=sys.stderr)
            continue
        print('\n%s: %d missing, %d obsolete'
              % (name, len(missing), len(obsolete)), file=sys.stderr)
        for msgid in missing:
            print('  missing  %r' % msgid, file=sys.stderr)
        for msgid in obsolete:
            print('  obsolete %r' % msgid, file=sys.stderr)


def main():
    entries = {}
    order = []
    for root in SRC:
        for name in sorted(os.listdir(root)):
            if not name.endswith(('.cpp', '.hpp') + UI_EXTENSIONS):
                continue
            path = os.path.join(root, name)
            for line, msgid, plural in scan(path):
                key = (msgid, plural)
                if key not in entries:
                    entries[key] = []
                    order.append(key)
                # The real relative path, not a hard-coded root. A reference
                # claiming a uicore file lives under a frontend sends a
                # translator to a file that is not there.
                entries[key].append(
                    '%s:%d' % (os.path.relpath(path, ROOT).replace(os.sep, '/'), line))

    with io.open(OUT, 'w', encoding='utf-8', newline='\n') as out:
        out.write(HEADER)
        # A msgid is a key, so it may appear once. An EXTERNAL row whose English
        # a frontend also marks for itself would otherwise come out twice -- a
        # catalogue with two entries under one key, undefined which one a lookup
        # gets, and not a valid .mo. The source's own row wins, because it is
        # the one with a file and a line number on it.
        marked = {msgid for msgid, _plural in order}
        for note, msgid in EXTERNAL:
            if msgid in marked:
                continue
            marked.add(msgid)
            out.write(note)
            out.write(po_field('msgid', msgid))
            out.write('msgstr ""\n\n')
        for msgid, plural in order:
            out.write('#: ' + ' '.join(entries[(msgid, plural)]) + '\n')
            out.write(po_field('msgid', msgid))
            if plural is None:
                out.write('msgstr ""\n\n')
            else:
                out.write(po_field('msgid_plural', plural))
                out.write('msgstr[0] ""\nmsgstr[1] ""\n\n')

    print('%d messages -> %s' % (len(marked), OUT), file=sys.stderr)
    report_drift(marked)


main()
