#!/usr/bin/env python3
"""Regenerates app/locale/xpcog.pot from the marked strings in app/src.

What xgettext would do, and it is here for the reason cmake/CompileCatalog.cmake
exists rather than a call to msgfmt: gettext is not a tool this project needs
anywhere else, and the one platform most of this is built on is the one least
likely to have it. Python is not a build dependency either -- nothing in CMake
runs this -- but a template is regenerated by a person once in a while, not by
CI on every commit, and asking that person for a Python they already have is a
much smaller imposition than asking for a gettext they do not.

    python tools/extract-messages.py

It reads `_()`, `wxPLURAL()`, `wxTRANSLATE()` and this project's own `trUtf8()`,
and nothing else. Adjacent string literals are joined, so a message wrapped
across four lines comes out as one.

It also **refuses to write a template** when a message whose English is not pure
ASCII has been marked with `_()` or `wxPLURAL()` rather than `trUtf8()`. See the
second half of the rule in `app/src/Text.hpp`: those two let the literal convert
to a wxString implicitly, which on Windows goes through the current 8-bit locale
and turns an em dash into two characters of mojibake -- in the lookup key *and*
in what is shown when the lookup misses. Nothing else in the build can catch it,
because it compiles and because an ASCII test fixture never sees it.

Escapes are decoded and the .pot carries raw UTF-8, which is what every other .po
in the world does and what the catalogue compiler wants: it copies the msgid into
a C++ string literal verbatim, and app/src is compiled with /utf-8.

**It does not merge.** The output is a fresh template; app/locale/*.po are
updated against it by hand or with msgmerge if you have one. Diffing the new
template against the committed one is how you find what a change added.
"""
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'app', 'src')
OUT = os.path.join(ROOT, 'app', 'locale', 'xpcog.pot')

STRING = re.compile(r'\s*"((?:[^"\\]|\\.)*)"')
KEYWORD = re.compile(r'(?<![A-Za-z0-9_])(_|wxTRANSLATE|wxPLURAL|trUtf8)\(')

# The two that convert their literal implicitly, and so may only carry ASCII.
ASCII_ONLY = ('_', 'wxPLURAL')

SIMPLE = {'n': '\n', 't': '\t', 'r': '\r', '\\': '\\', '"': '"', "'": "'"}

# Messages shown by the application but written somewhere the scan cannot see
# them. Only core's playlist headings so far: core links no toolkit and so has no
# `_()` to mark them with, and PlaylistDataModel looks them up by their English
# text -- see the comment there. Every one but this is also an info-panel field
# and is therefore already found above.
EXTERNAL = [
    ("#. The playlist's track-number column heading. A symbol rather than a\n"
     "#. word, and it has to stay short: the column is 44 dialog units wide.\n"
     "#: core/src/library/PlaylistView.cpp\n", "#"),
]

# wxWidgets' own stock labels, for the buttons this application does not put a
# label on itself -- Close, OK, Cancel, Yes, No on the standard dialog button
# sizers.
#
# They belong here because wx looks them up with a plain `_()`, which is
# wxGetTranslation with no domain, and that searches *every* loaded catalogue.
# So ours can answer them. It has to: vcpkg's wxwidgets port installs none of
# wx's own .mo files, so without these rows the buttons stay English in an
# otherwise translated dialog -- which is exactly how they shipped.
#
# Both spellings of each, because the mnemonic form is what a button asks for
# and the plain one is what wxMSW substitutes for Cancel, whose mnemonic it
# drops to match the native dialogs.
STOCK = [
    "&Close", "Close",
    "&OK", "OK",
    "&Cancel", "Cancel",
    "&Yes", "Yes",
    "&No", "No",
]

HEADER = '''# XPCog, the wxWidgets port of Cog.
# Copyright (C) 2026 the XPCog authors.
# This file is distributed under the same licence as XPCog.
#
# Regenerated with tools/extract-messages.py; see app/locale/README.md.
#
msgid ""
msgstr ""
"Project-Id-Version: XPCog\\n"
"Report-Msgid-Bugs-To: https://github.com/losnoco/XPCog/issues\\n"
"Language: \\n"
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\\n"

'''


def decode(raw):
    """C escapes to text.

    `\\xNN` is read as exactly two digits, which is how app/src writes them --
    and why a couple of those sources split a literal in two, so that the digits
    of the text after an escape are not swallowed by it.
    """
    out = bytearray()
    i = 0
    while i < len(raw):
        if raw[i] != '\\':
            out += raw[i].encode('utf-8')
            i += 1
            continue
        kind = raw[i + 1]
        if kind == 'x':
            out.append(int(raw[i + 2:i + 4], 16))
            i += 4
        else:
            out += SIMPLE[kind].encode('utf-8')
            i += 2
    return out.decode('utf-8')


def escape(text):
    return (text.replace('\\', '\\\\').replace('"', '\\"')
                .replace('\n', '\\n').replace('\t', '\\t'))


def po_field(keyword, text):
    """One PO field, broken at newlines the way gettext writes a long message."""
    if '\n' not in text and len(text) < 68:
        return '%s "%s"\n' % (keyword, escape(text))

    pieces = []
    lines = text.split('\n')
    for index, line in enumerate(lines):
        if index < len(lines) - 1:
            line += '\n'
        elif not line:
            continue
        pieces.append(line)

    return '%s ""\n' % keyword + ''.join('"%s"\n' % escape(p) for p in pieces)


def read_literal(text, i):
    parts = []
    while True:
        match = STRING.match(text, i)
        if not match:
            break
        parts.append(match.group(1))
        i = match.end()
    return decode(''.join(parts)), i


def scan(path, complaints):
    text = io.open(path, encoding='utf-8').read()
    found = []
    for match in KEYWORD.finditer(text):
        keyword = match.group(1)
        value, i = read_literal(text, match.end())
        # `_(` also matches a member being initialised -- `settings_(settings)`
        # -- and those have no string literal after them. `trUtf8(` matches its
        # own two overloads and, harmlessly, a call taking a variable.
        if not value:
            continue
        line = text.count('\n', 0, match.start()) + 1

        plural = None
        # trUtf8's plural overload takes the same three arguments wxPLURAL does,
        # so a second literal after a comma is what distinguishes them.
        if keyword in ('wxPLURAL', 'trUtf8') and i < len(text) and text[i] == ',':
            plural, i = read_literal(text, i + 1)
        if keyword == 'wxPLURAL' and plural is None:
            raise SystemExit('%s:%d: wxPLURAL needs two literals' % (path, line))

        if keyword in ASCII_ONLY and not (value + (plural or '')).isascii():
            complaints.append(
                '%s:%d: %s() carries a non-ASCII message; use trUtf8()'
                % (os.path.relpath(path, ROOT), line, keyword))

        found.append((line, value, plural))
    return found


def main():
    entries = {}
    order = []
    complaints = []
    for name in sorted(os.listdir(SRC)):
        if not name.endswith(('.cpp', '.hpp')):
            continue
        for line, msgid, plural in scan(os.path.join(SRC, name), complaints):
            key = (msgid, plural)
            if key not in entries:
                entries[key] = []
                order.append(key)
            entries[key].append('app/src/%s:%d' % (name, line))

    # Before writing anything: a template regenerated from sources carrying this
    # fault would bake the mangling into every .po that was updated against it.
    if complaints:
        for complaint in complaints:
            print(complaint, file=sys.stderr)
        raise SystemExit('%d message(s) marked with the wrong macro; see '
                         'app/src/Text.hpp' % len(complaints))

    with io.open(OUT, 'w', encoding='utf-8', newline='\n') as out:
        out.write(HEADER)
        # A msgid is a key, so it may appear once. Several of the stock labels
        # are words this application also marks for itself -- Cancel is a button
        # on the Last.fm pane as well as wx's -- and emitting both would produce
        # a catalogue with two entries under one key: undefined which one a
        # lookup gets, and not a valid .mo. The source's own row wins, because it
        # is the one with a file and a line number on it.
        marked = {msgid for msgid, _plural in order}
        for note, msgid in EXTERNAL:
            if msgid in marked:
                continue
            marked.add(msgid)
            out.write(note)
            out.write(po_field('msgid', msgid))
            out.write('msgstr ""\n\n')
        for msgid in STOCK:
            if msgid in marked:
                continue
            marked.add(msgid)
            out.write('#. A wxWidgets stock label. See STOCK in '
                      'tools/extract-messages.py.\n')
            out.write('#: wxWidgets/src/common/stockitem.cpp\n')
            out.write(po_field('msgid', msgid))
            out.write('msgstr ""\n\n')
        for msgid, plural in order:
            out.write('#: ' + ' '.join(entries[(msgid, plural)]) + '\n')
            out.write(po_field('msgid', msgid))
            if plural is None:
                out.write('msgstr ""\n\n')
            else:
                out.write(po_field('msgid_plural', plural))
                out.write('msgstr[0] ""\nmsgstr[1] ""\n\n')

    print('%d messages -> %s' % (len(marked), OUT), file=sys.stderr)


main()
