// The OpenAPI document, generated by walking the table the router dispatches
// from.
//
// This is the whole reason Route carries an operationId, a summary and schema
// names it does not need in order to dispatch. A hand-written document beside a
// hand-written router is two descriptions of one thing, and they agree until the
// first change that touches only one of them -- which is always, eventually, and
// silently. Generating one from the other means the document cannot describe an
// endpoint that does not exist, or miss one that does.
//
// What it cannot check by construction is that the pieces are filled in
// sensibly, so tests/core/test_remote_openapi.cpp does: unique operation ids,
// every path placeholder declared, every schema name resolving, no orphans, and
// every $ref in the emitted document pointing at something.

#include "Routes.hpp"

#include "xpcog/core/Version.hpp"
#include "xpcog/core/remote/RemoteServer.hpp"

#include <nlohmann/json.hpp>

#include <string>

namespace xpcog::remote {
namespace {

std::string lowerMethod(Method method) {
    std::string name{methodName(method)};
    for (char& c : name) {
        c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
    }
    return name;
}

nlohmann::json ref(std::string_view schema) {
    return {{"$ref", "#/components/schemas/" + std::string{schema}}};
}

nlohmann::json errorResponse(std::string_view description) {
    return {{"description", description},
            {"content", {{"application/json", {{"schema", ref("Error")}}}}}};
}

/// The failures every route can produce, added once rather than restated
/// thirty times. A generated client that handles 401 and 503 for one endpoint
/// handles them for all of them, which is true and worth saying.
void addCommonErrors(nlohmann::json& responses, bool writes, bool hasPath) {
    responses["400"] = errorResponse("The request was malformed.");
    responses["401"] = errorResponse("No bearer token, or the wrong one.");
    if (writes) {
        responses["403"] = errorResponse("This server is configured read-only.");
        responses["409"] =
            errorResponse("A track is starting or stopping; try again shortly.");
    }
    if (hasPath) {
        responses["404"] = errorResponse("No such track, key, preset or job.");
    }
    responses["405"] = errorResponse("That endpoint does not take this method.");
    responses["413"] = errorResponse("The request body is too large.");
    responses["503"] =
        errorResponse("The player did not answer in time. Retry-After says when.");
}

}  // namespace

std::string RemoteServer::openApiDocument() {
    nlohmann::json document;
    document["openapi"] = "3.1.0";

    document["info"]["title"]   = "XPCog";
    document["info"]["version"] = kVersionString;
    document["info"]["description"] =
        "Remote control for the XPCog audio player.\n\n"
        "Every request needs `Authorization: Bearer <token>`, including this "
        "document; the token is in the player's Preferences under Remote. There "
        "is no exemption for loopback.\n\n"
        "Track ids are scoped to a session. `Status.sessionId` and "
        "`Status.playlistRevision` are how a client notices that what it cached "
        "no longer means what it meant.\n\n"
        "Writes that change the DSP report `appliesFrom`, because not all of "
        "them are audible at once: the equaliser moves what is already playing, "
        "and a ReplayGain mode is read when the next track opens.";

    // Named as a scheme so a generated client asks for one, and applied globally
    // rather than per route -- the exceptions are the docs page and its two
    // assets, which are not in this document at all.
    document["components"]["securitySchemes"]["bearerAuth"] = {
        {"type", "http"}, {"scheme", "bearer"}};
    document["security"] = nlohmann::json::array({{{"bearerAuth", nlohmann::json::array()}}});

    for (const Schema& schema : schemas()) {
        document["components"]["schemas"][std::string{schema.name}] = schema.build();
    }

    nlohmann::json paths = nlohmann::json::object();
    for (const Route& route : routes()) {
        nlohmann::json operation;
        operation["operationId"] = route.operationId;
        operation["summary"]     = route.summary;

        if (!route.params.empty()) {
            nlohmann::json parameters = nlohmann::json::array();
            for (const Param& param : route.params) {
                nlohmann::json entry;
                entry["name"]        = param.name;
                entry["in"]          = param.in == In::Path ? "path" : "query";
                entry["required"]    = param.in == In::Path ? true : param.required;
                entry["description"] = param.description;
                entry["schema"]      = {{"type", param.type}};
                parameters.push_back(std::move(entry));
            }
            operation["parameters"] = std::move(parameters);
        }

        if (!route.requestSchema.empty()) {
            operation["requestBody"] = {
                {"required", true},
                {"content",
                 {{"application/json", {{"schema", ref(route.requestSchema)}}}}}};
        }

        nlohmann::json responses;
        const std::string ok = route.deferred ? "202" : "200";
        if (route.responseSchema.empty()) {
            // Artwork: bytes, and the media type says which kind.
            responses[ok] = {
                {"description", "Success."},
                {"content",
                 {{std::string{route.responseMedia},
                   {{"schema", {{"type", "string"}, {"format", "binary"}}}}}}}};
        } else {
            responses[ok] = {
                {"description", route.deferred ? "Accepted; follow the job."
                                               : "Success."},
                {"content",
                 {{std::string{route.responseMedia},
                   {{"schema", ref(route.responseSchema)}}}}}};
        }
        addCommonErrors(responses, route.writes,
                        route.path.find('{') != std::string_view::npos);
        operation["responses"] = std::move(responses);

        paths[std::string{route.path}][lowerMethod(route.method)] = std::move(operation);
    }
    document["paths"] = std::move(paths);

    return document.dump(2);
}

}  // namespace xpcog::remote
