# The generator behind xpcog_embed_resources(). Runs in script mode (cmake -P).
#
# Inputs, all as -D arguments:
#   XPCOG_RES_NAME   the lookup function's name, inside namespace xpcog::resources
#   XPCOG_RES_BASE   the directory paths are reported relative to
#   XPCOG_RES_FILES  semicolon-separated absolute paths
#   XPCOG_RES_CPP    where to write the definitions
#   XPCOG_RES_HPP    where to write the declaration

foreach(_required NAME BASE FILES CPP HPP)
    if(NOT DEFINED XPCOG_RES_${_required})
        message(FATAL_ERROR "EmbedResources.cmake: XPCOG_RES_${_required} not set")
    endif()
endforeach()

set(_arrays "")
set(_entries "")

foreach(_f IN LISTS XPCOG_RES_FILES)
    if(NOT EXISTS "${_f}")
        message(FATAL_ERROR "EmbedResources.cmake: no such file: ${_f}")
    endif()

    file(RELATIVE_PATH _rel "${XPCOG_RES_BASE}" "${_f}")
    string(MAKE_C_IDENTIFIER "${_rel}" _sym)

    file(READ "${_f}" _hex HEX)

    if(_hex STREQUAL "")
        # A zero-length array is not valid C++, so an empty file becomes a
        # one-byte array reported with a length of zero.
        set(_body "0x00")
        set(_size "0")
    else()
        # Wrapped before expansion: the line-break pass then runs over the hex
        # rather than over the five-times-larger text it becomes, which for the
        # SC-55 background -- 776 KiB, the one genuinely large resource here --
        # is the difference between a slow configure step and a tolerable one.
        string(REGEX REPLACE "(................................)" "\\1;" _hex "${_hex}")
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _body "${_hex}")
        string(REPLACE ";" "\n    " _body "${_body}")
        set(_body "    ${_body}")
        set(_size "sizeof(k_${_sym})")
    endif()

    string(APPEND _arrays "const unsigned char k_${_sym}[] = {\n${_body}\n};\n\n")
    string(APPEND _entries "    {\"${_rel}\", k_${_sym}, ${_size}},\n")
endforeach()

set(_guard_name "${XPCOG_RES_NAME}")

file(WRITE "${XPCOG_RES_HPP}"
"// Generated by cmake/EmbedResources.cmake. Do not edit.
#pragma once

#include <cstddef>
#include <span>
#include <string_view>

namespace xpcog::resources {

/// The bytes of an embedded file, addressed by its path relative to the
/// directory it was embedded from. Empty when there is no such resource, which
/// is the caller's cue that a filename was renamed without the CMake list being
/// updated -- the failure Qt's resource system reported the same way.
[[nodiscard]] std::span<const std::byte> ${_guard_name}(std::string_view path);

}  // namespace xpcog::resources
")

file(WRITE "${XPCOG_RES_CPP}"
"// Generated by cmake/EmbedResources.cmake. Do not edit.
#include \"${_guard_name}_resources.hpp\"

namespace xpcog::resources {
namespace {

${_arrays}struct Entry {
    std::string_view     path;
    const unsigned char* data;
    std::size_t          size;
};

const Entry kEntries[] = {
${_entries}};

}  // namespace

std::span<const std::byte> ${_guard_name}(std::string_view path) {
    for (const Entry& entry : kEntries) {
        if (entry.path == path) {
            return {reinterpret_cast<const std::byte*>(entry.data), entry.size};
        }
    }
    return {};
}

}  // namespace xpcog::resources
")
