# The Windows App SDK, for the WinUI 3 player in app-winui/.
#
# Microsoft ships it only as NuGet packages whose build logic is MSBuild .targets
# files, so nothing here can be "found": the packages are fetched as the zip
# archives a .nupkg is, and the three things a C++ consumer actually needs from
# them are wired up by hand --
#
#   1. Projection headers. The packages carry .winmd metadata, not C++/WinRT
#      headers, so they are generated at configure time. With the Windows SDK's
#      own cppwinrt.exe, deliberately: the Windows.* headers platform/ already
#      uses come from that SDK, and a projection generated by a different
#      cppwinrt would put two different winrt/base.h definitions in one program.
#   2. The bootstrapper. An unpackaged process finds the installed Windows App
#      Runtime framework package through Microsoft.WindowsAppRuntime.Bootstrap.dll,
#      which is linked here and staged next to the executable.
#   3. Nothing else to link: WinRT classes are activated by name.
#
# No XAML compiler: the interface is built in code, with the odd template read
# from XAML text at run time. The runtime itself is not shipped -- it is the
# framework package Windows installs separately; the installer fetches it where
# it is missing (packaging/windows/WindowsAppRuntime.ps1).
#
# Only the three sub-packages that hold those are fetched, plus WebView2, whose
# metadata the WinUI controls refer to and so cannot be projected without. The
# Microsoft.WindowsAppSDK metapackage depends on ten, several of them hundreds of
# megabytes of AI and ML runtime this has no use for; the version information
# the Runtime package would add is three numbers, set below instead.

include(FetchContent)

set(XPCOG_WINAPPSDK_RUNTIME_MAJOR 2)
set(XPCOG_WINAPPSDK_RUNTIME_MINOR 5)
set(XPCOG_WINAPPSDK_RUNTIME_PATCH 1)

# Microsoft's runtime installer for that version, which the Windows installer
# fetches on a machine that does not have the runtime yet -- 120 MB, which is
# why it is fetched rather than carried -- and which CI installs before the
# WinUI tests. Pinned and hashed together with the version above: a bump of one
# is a bump of all three.
set(XPCOG_WINAPPSDK_RUNTIME_INSTALLER_URL
    "https://aka.ms/windowsappsdk/2.5/2.5.1/windowsappruntimeinstall-x64.exe")
set(XPCOG_WINAPPSDK_RUNTIME_INSTALLER_SHA256
    "931a421e8dc3e6e67724806cb67fecdbb88dfe323f0170842eb4a4b4b149f1e2")

# name|NuGet id|version|sha256 -- the versions Microsoft.WindowsAppSDK 2.5.1 pins.
set(_winappsdk_packages
    "foundation|microsoft.windowsappsdk.foundation|2.3.12|ce04d01d68cb16b5dc85a5c9efb8162dba876bc2e5b766b5968979899d4efa9e"
    "interactiveexperiences|microsoft.windowsappsdk.interactiveexperiences|2.1.9|f9159d73e3e46717f159606e43b4acf8336aaff5bdd4d395fe3a93fdb41437ac"
    "winui|microsoft.windowsappsdk.winui|2.3.9|d36145bd6c0f46fc04e07fb4af365d093fb42c39b625948d0ead07a0b26fce96"
    "webview2|microsoft.web.webview2|1.0.3719.77|2f6be3a10a1a8d6d1fde986af4131dab344f8181fffe75590824e0f4b037ed73")

# Win2D, for the WinUI player's painted panes -- the spectrum, the
# oscilloscope, the waveform seek bar, the SC-55. It is not part of the Windows
# App Runtime: its DLL ships beside the executable, and its classes are
# activated from that DLL directly rather than looked up by the system -- see
# app-winui/src/Win2D.cpp.
#
# 1.4.0 is built against WinUI 1.8 and runs here on the 2.x runtime. That
# leans on WinUI keeping its interfaces stable across the major version,
# which is a bet worth knowing is being made.
list(APPEND _winappsdk_packages
    "win2d|microsoft.graphics.win2d|1.4.0|e13866088b3c50205aae36e9e4cb3c23b21d11c4b4590ddcbeaafa9ea2c79f48")

foreach(_entry IN LISTS _winappsdk_packages)
    string(REPLACE "|" ";" _entry "${_entry}")
    list(GET _entry 0 _name)
    list(GET _entry 1 _id)
    list(GET _entry 2 _version)
    list(GET _entry 3 _hash)
    # DOWNLOAD_NAME is what makes the archive extract: CMake decides by
    # extension, and it does not know .nupkg is a zip.
    FetchContent_Declare(winappsdk_${_name}
        URL "https://api.nuget.org/v3-flatcontainer/${_id}/${_version}/${_id}.${_version}.nupkg"
        URL_HASH SHA256=${_hash}
        DOWNLOAD_NAME "${_id}.${_version}.zip")
    FetchContent_MakeAvailable(winappsdk_${_name})
    set(_winappsdk_${_name} "${winappsdk_${_name}_SOURCE_DIR}")
endforeach()

# The developer shell sets WindowsSdkVerBinPath to the SDK whose headers are on
# INCLUDE, which is the one whose cppwinrt.exe has to generate this projection.
find_program(XPCOG_CPPWINRT cppwinrt
    HINTS "$ENV{WindowsSdkVerBinPath}/x64"
    NO_DEFAULT_PATH)
if(NOT XPCOG_CPPWINRT)
    message(FATAL_ERROR
            "The WinUI player needs cppwinrt.exe from the Windows SDK; "
            "configure from a Visual Studio developer shell.")
endif()

file(GLOB _winappsdk_winmds
    "${_winappsdk_foundation}/metadata/*.winmd"
    "${_winappsdk_interactiveexperiences}/metadata/10.0.17763.0/*.winmd"
    "${_winappsdk_winui}/metadata/*.winmd"
    "${_winappsdk_webview2}/lib/*.winmd")
list(APPEND _winappsdk_winmds "${_winappsdk_win2d}/lib/uap10.0/Microsoft.Graphics.Canvas.winmd")
set(XPCOG_WIN2D_DLL "${_winappsdk_win2d}/runtimes/win-x64/native/Microsoft.Graphics.Canvas.dll")

# Regenerated only when the inputs or the generator change; it takes a while and
# writes a few hundred headers.
set(_projection "${CMAKE_BINARY_DIR}/winappsdk/include")
string(SHA256 _stamp_value "${XPCOG_CPPWINRT};${_winappsdk_winmds}")
set(_stamp "${CMAKE_BINARY_DIR}/winappsdk/projection.stamp")
set(_previous "")
if(EXISTS "${_stamp}")
    file(READ "${_stamp}" _previous)
endif()
if(NOT _previous STREQUAL _stamp_value)
    message(STATUS "Generating the Windows App SDK C++/WinRT projection")
    file(REMOVE_RECURSE "${_projection}")
    set(_args)
    foreach(_winmd IN LISTS _winappsdk_winmds)
        list(APPEND _args -in "${_winmd}")
    endforeach()
    execute_process(
        COMMAND "${XPCOG_CPPWINRT}" ${_args} -ref sdk -out "${_projection}"
        RESULT_VARIABLE _result
        OUTPUT_VARIABLE _output
        ERROR_VARIABLE _output)
    if(NOT _result EQUAL 0)
        message(FATAL_ERROR "cppwinrt failed:\n${_output}")
    endif()
    file(WRITE "${_stamp}" "${_stamp_value}")
endif()

add_library(xpcog-winappsdk INTERFACE)
add_library(XPCog::winappsdk ALIAS xpcog-winappsdk)
target_include_directories(xpcog-winappsdk SYSTEM INTERFACE
    "${_projection}"
    "${_winappsdk_foundation}/include"
    "${_winappsdk_interactiveexperiences}/include"
    "${_winappsdk_winui}/include")
target_link_libraries(xpcog-winappsdk INTERFACE
    "${_winappsdk_foundation}/lib/native/x64/Microsoft.WindowsAppRuntime.Bootstrap.lib"
    WindowsApp.lib)
target_compile_definitions(xpcog-winappsdk INTERFACE
    XPCOG_WINAPPSDK_RUNTIME_MAJOR=${XPCOG_WINAPPSDK_RUNTIME_MAJOR}
    XPCOG_WINAPPSDK_RUNTIME_MINOR=${XPCOG_WINAPPSDK_RUNTIME_MINOR}
    XPCOG_WINAPPSDK_RUNTIME_PATCH=${XPCOG_WINAPPSDK_RUNTIME_PATCH})
# The generated XAML headers are large enough to overflow the default section
# count of an object file.
target_compile_options(xpcog-winappsdk INTERFACE /bigobj)

set(XPCOG_WINAPPSDK_BOOTSTRAP_DLL
    "${_winappsdk_foundation}/runtimes/win-x64/native/Microsoft.WindowsAppRuntime.Bootstrap.dll")
