// See OrganyaSynth.hpp for what this is and where it came from.
//
// The structure follows Bisqwit's original because the format is defined by it
// as much as by any specification: the note-to-frequency constant, the master
// volume, and the Lanczos window on the wavetable lookup are all choices this
// player made and every Organya listener has since heard. Deviating from them
// would not be a better reading of the format, it would be a different player.
//
// What has changed is everything around the arithmetic: the file readers, which
// took a FILE* and now take bytes; the drum and waveform data, which came from
// a bundle and are now compiled in; and the seek path, which did not exist.

#include "OrganyaSynth.hpp"

#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <cstring>
#include <string>
#include <string_view>
#include <utility>

/// The compiled-in data, generated by codecs/organya/CMakeLists.txt.
///
/// The parameter files are addressed by the number in their name -- fx96.pxt is
/// 0x96 -- rather than by position, so the patch table below reads the way the
/// format writes it and adding a drum is a matter of dropping a file in.
extern "C" {
extern const unsigned char kOrganyaWaveTable[];
extern const unsigned int  kOrganyaWaveTableSize;

extern const unsigned int         kOrganyaPxtCount;
extern const unsigned int         kOrganyaPxtId[];
extern const unsigned char* const kOrganyaPxtData[];
extern const unsigned int         kOrganyaPxtSize[];
}

namespace xpcog::organya {
namespace {

//========= Reading the file ========//

/// A cursor over the file's bytes with the format's own integer widths.
///
/// Everything in an .org file is little-endian and unsigned, and a read past
/// the end answers -1 rather than throwing -- which is what the original's
/// fgetc() did, and which the loader below checks for by validating what it
/// read rather than by asking whether the read succeeded.
class Reader {
public:
    explicit Reader(std::span<const std::byte> data) : data_(data) {}

    [[nodiscard]] int byte() {
        if (at_ >= data_.size()) {
            exhausted_ = true;
            return -1;
        }
        return static_cast<int>(static_cast<unsigned char>(data_[at_++]));
    }
    [[nodiscard]] int word() {
        const int low  = byte();
        const int high = byte();
        return (high << 8) + low;
    }
    [[nodiscard]] int dword() {
        const int low  = word();
        const int high = word();
        return (high << 16) + low;
    }

    /// True once any read has run off the end. The loader asks this once, at
    /// the end, rather than after every field: a truncated file is a truncated
    /// file whichever field it stopped on.
    [[nodiscard]] bool exhausted() const { return exhausted_; }

    [[nodiscard]] bool match(std::string_view signature) {
        if (data_.size() < signature.size()) {
            return false;
        }
        const bool same = std::memcmp(data_.data(), signature.data(), signature.size()) == 0;
        at_ = signature.size();
        return same;
    }

private:
    std::span<const std::byte> data_;
    std::size_t                at_        = 0;
    bool                       exhausted_ = false;
};

//========= PART 1 : SOUND EFFECT PLAYER (PXT) ========//

/// The six waveforms every PixTone generator is built from.
///
/// Bit-exact with PixTone v1.0.3, including the pseudorandom one -- the LFSR is
/// stepped once per sample whether or not that sample is the one being written,
/// so the noise waveform depends on having run the whole loop in order.
struct Waveforms {
    signed char shape[6][256]{};

    Waveforms() {
        unsigned seed = 0;
        for (unsigned i = 0; i < 256; ++i) {
            seed = (seed * 214013) + 2531011;  // Linear congruential generator
            shape[0][i] = static_cast<signed char>(
                0x40 * std::sin(static_cast<double>(i) * 3.1416 / 0x80));  // Sine
            shape[1][i] = static_cast<signed char>(((0x40 + i) & 0x80) != 0 ? 0x80 - i
                                                                            : i);  // Triangle
            shape[2][i] = static_cast<signed char>(-0x40 + (i / 2));  // Sawtooth up
            shape[3][i] = static_cast<signed char>(0x40 - (i / 2));   // Sawtooth down
            shape[4][i] = static_cast<signed char>(0x40 - (i & 0x80));  // Square
            shape[5][i] = static_cast<signed char>(seed >> 16) / 2;     // Pseudorandom
        }
    }
};

/// Reads the numeric values out of a PixTone parameter file: one per line,
/// after a colon, blank lines ignored.
///
/// PixTone wrote these as plain text and the original player parsed them with
/// fgets and strtod, so this is deliberately as forgiving: a line with no colon
/// reads as zero, and running off the end reads as zero for ever. The six files
/// shipped here are well-formed, and a parser that rejected anything else would
/// only make it harder to drop in a replacement drum kit.
class PxtReader {
public:
    explicit PxtReader(std::string_view text) : text_(text) {}

    [[nodiscard]] double value() {
        while (at_ < text_.size()) {
            const std::size_t lineEnd = std::min(text_.find('\n', at_), text_.size());
            std::string_view  line    = text_.substr(at_, lineEnd - at_);
            at_                       = lineEnd + 1;

            if (!line.empty() && line.back() == '\r') {
                line.remove_suffix(1);
            }
            if (line.empty()) {
                continue;  // Blank line: try the next one.
            }

            const std::size_t colon = line.find(':');
            if (colon == std::string_view::npos) {
                return 0.0;
            }
            // strtod wants a terminator; the line is a view into a byte array
            // that has none, so this is the one copy in the parse.
            const std::string tail{line.substr(colon + 1)};
            return std::strtod(tail.c_str(), nullptr);
        }
        return 0.0;
    }

    [[nodiscard]] int integer() { return static_cast<int>(value()); }

private:
    std::string_view text_;
    std::size_t      at_ = 0;
};

/// One PixTone channel: three signal generators feeding an envelope.
struct PxtChannel {
    struct Wave {
        const signed char* wave   = nullptr;
        double             pitch  = 0.0;
        int                level  = 0;
        int                offset = 0;
    };

    /// Linearly interpolated between an initial value and three key points.
    struct Envelope {
        int initial = 0;
        struct Point {
            int time = 0;
            int val  = 0;
        } p[3];

        [[nodiscard]] int evaluate(int i) const {
            int prevval = initial, prevtime = 0;
            int nextval = 0, nexttime = 256;
            for (int j = 2; j >= 0; --j) {
                if (i < p[j].time) {
                    nexttime = p[j].time;
                    nextval  = p[j].val;
                }
            }
            for (int j = 0; j <= 2; ++j) {
                if (i >= p[j].time) {
                    prevtime = p[j].time;
                    prevval  = p[j].val;
                }
            }
            if (nexttime <= prevtime) {
                return prevval;
            }
            return ((i - prevtime) * (nextval - prevval) / (nexttime - prevtime)) + prevval;
        }
    };

    bool     enabled  = false;
    int      nsamples = 0;
    Wave     carrier;    // The main signal to be generated.
    Wave     frequency;  // Modulator to the main signal.
    Wave     amplitude;  // Modulator to the main signal.
    Envelope envelope;

    [[nodiscard]] std::vector<int> synth() const {
        // nsamples reaches the divisions below, so a file claiming zero or a
        // negative length is refused here rather than dividing by it. The
        // original trusted the file; these six are trustworthy and a
        // replacement need not be.
        if (!enabled || nsamples <= 0) {
            return {};
        }
        std::vector<int> result(static_cast<std::size_t>(nsamples));

        const double count     = nsamples;
        double       mainpos   = carrier.offset;
        const double maindelta = 256 * carrier.pitch / count;

        for (std::size_t i = 0; i < result.size(); ++i) {
            const auto position = [&](double pitch) {
                return 256 * pitch * static_cast<double>(i) / count;
            };
            // Take a sample from each of the three signal generators:
            const int freqval =
                frequency.wave[0xFF & static_cast<int>(frequency.offset +
                                                       position(frequency.pitch))] *
                frequency.level;
            const int ampval =
                amplitude.wave[0xFF & static_cast<int>(amplitude.offset +
                                                       position(amplitude.pitch))] *
                amplitude.level;
            const int mainval =
                carrier.wave[0xFF & static_cast<int>(mainpos)] * carrier.level;

            // Apply amplitude and envelope to the main signal level:
            result[i] = mainval * (ampval + 4096) / 4096 *
                        envelope.evaluate(static_cast<int>(position(1.0))) / 4096;
            // Apply frequency modulation to maindelta:
            mainpos += maindelta * (1 + (freqval / (freqval < 0 ? 8192. : 2048.)));
        }
        return result;
    }
};

/// The four parallel FM/AM modulators one .pxt file describes.
struct Pxt {
    PxtChannel channels[4];

    void load(std::string_view text, const Waveforms& shapes) {
        PxtReader in{text};
        // Written out field by field rather than as a braced initialiser. The
        // original relied on brace elision *and* on left-to-right evaluation
        // inside the braces to get sixteen reads in the right order, which is
        // correct C++11 but reads like a trap.
        const auto readWave = [&] {
            PxtChannel::Wave wave;
            // The model index selects one of six shapes. Masked rather than
            // taken modulo: a negative value would index behind the array, and
            // C++'s % keeps the sign.
            wave.wave   = shapes.shape[static_cast<unsigned>(in.integer()) % 6];
            wave.pitch  = in.value();
            wave.level  = in.integer();
            wave.offset = in.integer();
            return wave;
        };

        for (PxtChannel& channel : channels) {
            channel.enabled   = in.integer() != 0;
            channel.nsamples  = in.integer();
            channel.carrier   = readWave();
            channel.frequency = readWave();
            channel.amplitude = readWave();

            channel.envelope.initial = in.integer();
            for (PxtChannel::Envelope::Point& point : channel.envelope.p) {
                point.time = in.integer();
                point.val  = in.integer();
            }
        }
    }
};

}  // namespace

//========= The shared tables ========//

const Tables& Tables::shared() {
    /// 100 waveforms of 256 samples. Fixed by the format, not by the file.
    constexpr std::size_t kWaveBankSize = 100 * 256;

    static const Tables tables = [] {
        Tables built;

        // The waveform bank is 100 * 256 signed bytes and nothing else. Widened
        // to int16 here because the mixer indexes melodic and percussive
        // waveforms through the same pointer, and percussion does not fit in a
        // byte.
        //
        // Sized to the full bank whatever the file holds, so that a wave index
        // of 99 -- which the file is free to name -- reads zeros from a short
        // table rather than off the end of it.
        built.waveTable.assign(kWaveBankSize, 0);
        for (unsigned i = 0; i < kOrganyaWaveTableSize && i < kWaveBankSize; ++i) {
            built.waveTable[i] =
                static_cast<std::int16_t>(static_cast<signed char>(kOrganyaWaveTable[i]));
        }

        const Waveforms shapes;

        // Which .pxt file each of the twelve percussion slots plays. Six slots
        // name no file at all and stay silent; that is the format, not an
        // omission -- Cave Story's percussion uses six drums and Organya
        // reserved a dozen slots for them.
        static const unsigned patch[12] = {0x96, 0, 0x97, 0, 0x9a, 0x98,
                                           0x99, 0, 0x9b, 0, 0,    0};

        for (unsigned drum = 0; drum < 12; ++drum) {
            if (patch[drum] == 0) {
                continue;
            }
            unsigned file = kOrganyaPxtCount;
            for (unsigned candidate = 0; candidate < kOrganyaPxtCount; ++candidate) {
                if (kOrganyaPxtId[candidate] == patch[drum]) {
                    file = candidate;
                    break;
                }
            }
            if (file == kOrganyaPxtCount) {
                continue;  // No such parameter file: a silent slot.
            }

            Pxt parameters;
            parameters.load(
                std::string_view{reinterpret_cast<const char*>(kOrganyaPxtData[file]),
                                 kOrganyaPxtSize[file]},
                shapes);

            // Synthesise and mix the drum's four component channels. They are
            // not all the same length, so the sample grows to the longest.
            std::vector<std::int16_t>& sample = built.drums[drum];
            for (const PxtChannel& channel : parameters.channels) {
                const std::vector<int> rendered = channel.synth();
                if (rendered.size() > sample.size()) {
                    sample.resize(rendered.size());
                }
                for (std::size_t at = 0; at < rendered.size(); ++at) {
                    sample[at] = static_cast<std::int16_t>(sample[at] + rendered[at]);
                }
            }
        }
        return built;
    }();
    return tables;
}

//========= PART 2 : SONG PLAYER (ORG) ========//

bool Song::load(std::span<const std::byte> data, double sampleRate) {
    tables_ = &Tables::shared();

    Reader in{data};
    if (!in.match("Org-02")) {
        return false;
    }

    msPerBeat_ = in.word();
    (void)in.byte();  // steps_per_bar -- display only, the player never reads it
    (void)in.byte();  // beats_per_step -- likewise
    loopStart_ = in.dword();
    loopEnd_   = in.dword();

    // Every count below is read from the file and multiplied out into an
    // allocation, so each is bounded before it is trusted. The original read
    // straight into a vector sized by a 16-bit field, which cannot overflow but
    // can ask for 65,535 events that are not there -- and then read past the
    // end of the file for every one of them.
    std::size_t counts[kTracks]{};
    for (std::size_t track = 0; track < kTracks; ++track) {
        tracks_[track].tuning = in.word();
        tracks_[track].wave   = in.byte();
        tracks_[track].pi     = in.byte() != 0;
        counts[track]         = static_cast<std::size_t>(in.word());
    }
    if (in.exhausted()) {
        return false;
    }

    // Five parallel arrays per track: beat numbers first, then notes, lengths,
    // volumes and pannings, each complete before the next begins.
    for (std::size_t track = 0; track < kTracks; ++track) {
        std::vector<std::pair<int, Event>> events(counts[track]);
        for (auto& event : events) {
            event.first = in.dword();
        }
        for (auto& event : events) {
            event.second.note = in.byte();
        }
        for (auto& event : events) {
            event.second.length = in.byte();
        }
        for (auto& event : events) {
            event.second.volume = in.byte();
        }
        for (auto& event : events) {
            event.second.panning = in.byte();
        }
        if (in.exhausted()) {
            return false;
        }
        tracks_[track].events.insert(events.begin(), events.end());
    }

    sampleRate_ = sampleRate;
    // Truncated, not rounded, and the decoder's length calculation has to agree
    // with this or the track ends somewhere the audio does not. See the note in
    // OrganyaDecoder.cpp.
    samplesPerBeat_ =
        static_cast<std::size_t>(static_cast<double>(msPerBeat_) * sampleRate * 1e-3);
    if (msPerBeat_ <= 0 || samplesPerBeat_ == 0) {
        return false;
    }

    reset();
    return true;
}

void Song::reset() {
    beat_ = 0;
    for (Instrument& track : tracks_) {
        track.phaseacc    = 0.0;
        track.phaseinc    = 0.0;
        track.curVolume   = 0.0;
        track.curPan      = 0;
        track.curLength   = 0;
        track.curWaveSize = 0;
        track.curWave     = nullptr;
    }
}

void Song::startNote(Instrument& track, std::size_t index) {
    const auto found = track.events.find(beat_);
    if (found == track.events.end()) {
        return;
    }
    const Event& event = found->second;

    // 255 in any field means "carry on with what was already set".
    if (event.volume != 255) {
        // 4e-6 is the player's master volume and is the reason Organya comes
        // out at a listenable level at all: the waveforms are signed bytes and
        // sixteen tracks are summed without any headroom, so the scale factor
        // is doing the work a mixer would otherwise do. Loud songs can and do
        // exceed unity; see the note on clipping in OrganyaDecoder.cpp.
        constexpr double kMasterVolume = 4e-6;
        track.curVolume                = event.volume * kMasterVolume;
    }
    if (event.panning != 255) {
        track.curPan = event.panning;
    }
    if (event.note == 255) {
        return;
    }

    // Equal temperament, with the instrument's own tuning in thousandths of a
    // semitone. 155.376 puts note 44 at 440 Hz:
    //   12*log(256*440)/log(2) - (4*12-3-1)
    // -- 256 because the waveform being stepped through is 256 samples long, so
    // the frequency here is a sample rate rather than a pitch.
    const double freq =
        std::pow(2.0, (event.note + (track.tuning / 1000.0) + 155.376) / 12);

    track.phaseinc = freq / sampleRate_;
    track.phaseacc = 0.0;

    if (index < kFirstDrumTrack) {
        track.curWave     = &tables_->waveTable[256 * (track.wave % 100)];
        track.curWaveSize = 256;
        // In "pi" mode the note lasts exactly 1024 waveform samples whatever
        // length the event carries -- a fixed number of cycles rather than a
        // fixed duration, so it is shorter the higher the note.
        track.curLength =
            track.pi ? static_cast<std::int64_t>(1024 / track.phaseinc)
                     : static_cast<std::int64_t>(event.length) *
                           static_cast<std::int64_t>(samplesPerBeat_);
    } else {
        const std::vector<std::int16_t>& drum = tables_->drums[track.wave % 12];
        // Percussion is pitched linearly rather than by temperament: the note
        // number scales the playback rate of a 22,050 Hz sample directly.
        track.phaseinc    = event.note * (22050 / 32.5) / sampleRate_;
        track.curWave     = drum.data();
        track.curWaveSize = static_cast<std::int64_t>(drum.size());
        // Note 0 on a percussion track gives a rate of zero, which the original
        // divided by. It reaches this codec from any file that asks for it, so
        // it is a silent note rather than an infinity cast to an int.
        track.curLength =
            track.phaseinc > 0.0
                ? static_cast<std::int64_t>(static_cast<double>(drum.size()) / track.phaseinc)
                : 0;
    }

    // The six unfilled percussion slots land here.
    if (track.curWaveSize <= 0) {
        track.curLength = 0;
    }
}

void Song::renderBeat(float* out) {
    if (loopEnd_ > loopStart_ && beat_ == loopEnd_) {
        beat_ = loopStart_;
    }

    const auto frames = static_cast<std::int64_t>(samplesPerBeat_);
    if (out != nullptr) {
        std::fill_n(out, samplesPerBeat_ * 2, 0.0F);
    }

    for (std::size_t index = 0; index < kTracks; ++index) {
        Instrument& track = tracks_[index];
        startNote(track, index);

        const std::int64_t n = std::min(frames, track.curLength);
        if (n <= 0) {
            continue;
        }

        if (out != nullptr) {
            // Panning is a 0..12 dial with 6 in the middle, and each side is
            // clamped there -- so centre is full volume on both, not half.
            const double left  = (track.curPan > 6 ? 12 - track.curPan : 6) * track.curVolume;
            const double right = (track.curPan < 6 ? track.curPan : 6) * track.curVolume;

            for (std::int64_t p = 0; p < n; ++p) {
                const double pos = track.phaseacc + (static_cast<double>(p) * track.phaseinc);

                // A plain `curWave[unsigned(pos) % curWaveSize]` would do, and
                // is what the format's own player on the DS does. Lanczos-2 is
                // Bisqwit's addition and is audibly better on the low rumbles
                // that Organya's bass waveforms are mostly made of, so it is
                // part of what this format sounds like now.
                constexpr int radius  = 2;
                const auto    lanczos = [](double d) -> double {
                    if (d == 0.) {
                        return 1.;
                    }
                    if (std::fabs(d) > radius) {
                        return 0.;
                    }
                    const double dr = (d *= 3.14159265) / radius;
                    return std::sin(d) * std::sin(dr) / (d * dr);
                };

                // Widening the window when the waveform is being read slower
                // than one sample per output sample; narrowing it would alias.
                const double scale = 1 / track.phaseinc > 1 ? 1 : 1 / track.phaseinc;
                double       density = 0, sample = 0;
                // int64 rather than int: pos accumulates across a note that can
                // run for minutes at a phase increment of tens, which overflows
                // a 32-bit window index long before the note ends.
                const auto low  = static_cast<std::int64_t>((-radius / scale) + pos - 0.5);
                const auto high = static_cast<std::int64_t>((radius / scale) + pos + 0.5);
                for (std::int64_t m = low; m < high; ++m) {
                    const double factor = lanczos((static_cast<double>(m) - pos + 0.5) * scale);
                    density += factor;
                    sample += track.curWave[m < 0 ? 0 : m % track.curWaveSize] * factor;
                }
                if (density > 0.) {
                    sample /= density;
                }

                out[(p * 2) + 0] += static_cast<float>(sample * left);
                out[(p * 2) + 1] += static_cast<float>(sample * right);
            }
        }

        // Exactly what the loop above would have left behind, and the only
        // state it touches. See renderBeat()'s note in the header.
        //
        // The loop reads `phaseacc + p * phaseinc` rather than adding to
        // phaseacc each sample, which is what makes this line able to say
        // "exactly". The original accumulated, and a note held for a minute
        // accumulates a minute's worth of rounding into its own phase; this
        // form has none of that, and costs a multiply.
        track.phaseacc += track.phaseinc * static_cast<double>(n);
        track.curLength -= n;
    }

    ++beat_;
}

}  // namespace xpcog::organya
